version: '3.1'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: my_docker_app_dev    
  web:
    image: my_docker_app
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      APP_HOSTNAME: ${APP_HOSTNAME}
      APP_PORT: ${APP_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOSTNAME: database
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      COOL_TEXT: ${COOL_TEXT}
    depends_on:
      - database 
